/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Interface.grades.WindowManagementAcademic;
import Calendar.Calendar;
import Sesion.Sesion;

/**
 *
 * @author Alejandro
 */
public class WindowMain extends javax.swing.JFrame {

    /**
     * Creates new form WindowMain
     * @param actualSes
     */
    Sesion actualSes;
    public WindowMain(Sesion sesion) {
        
        initComponents();
        addCalendar();
        this.actualSes=sesion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void addCalendar(){
        Calendar myCalendar=new Calendar();
        
        this.getContentPane().add(myCalendar,new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 300, 500));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 640));
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        makeHomeworks = new javax.swing.JButton();
        managementAcademic = new javax.swing.JButton();
        contacts = new javax.swing.JButton();
        eventsCalendary = new javax.swing.JButton();
        library = new javax.swing.JButton();
        projects = new javax.swing.JButton();
        closeSesion = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        makeHomeworks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        makeHomeworks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/deberes_1.png"))); // NOI18N
        makeHomeworks.setText("Realizar Actividades");
        makeHomeworks.setBorderPainted(false);
        makeHomeworks.setFocusable(false);
        makeHomeworks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeHomeworksActionPerformed(evt);
            }
        });
        getContentPane().add(makeHomeworks, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 240, 80));

        managementAcademic.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        managementAcademic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/a-mejor-resultado-de-la-prueba.png"))); // NOI18N
        managementAcademic.setText("Gestion Academica");
        managementAcademic.setBorderPainted(false);
        managementAcademic.setFocusable(false);
        managementAcademic.setIconTextGap(10);
        managementAcademic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managementAcademicActionPerformed(evt);
            }
        });
        getContentPane().add(managementAcademic, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 240, 80));

        contacts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contacts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/CONTACTO.PNG"))); // NOI18N
        contacts.setText("Contactos");
        contacts.setBorderPainted(false);
        contacts.setFocusable(false);
        contacts.setIconTextGap(20);
        contacts.setMargin(new java.awt.Insets(2, 14, 2, 50));
        getContentPane().add(contacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 240, 80));

        eventsCalendary.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eventsCalendary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/interfaz.png"))); // NOI18N
        eventsCalendary.setText("Eventos Calendario");
        eventsCalendary.setBorderPainted(false);
        eventsCalendary.setFocusable(false);
        eventsCalendary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventsCalendaryActionPerformed(evt);
            }
        });
        getContentPane().add(eventsCalendary, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 240, 80));

        library.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        library.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/libro.png"))); // NOI18N
        library.setText("Biblioteca");
        library.setBorderPainted(false);
        library.setFocusable(false);
        library.setIconTextGap(20);
        library.setMargin(new java.awt.Insets(2, 14, 2, 50));
        library.setSelected(true);
        library.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libraryActionPerformed(evt);
            }
        });
        getContentPane().add(library, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 240, 80));

        projects.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        projects.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/proyect.jpg"))); // NOI18N
        projects.setText("Proyectos");
        projects.setBorderPainted(false);
        projects.setFocusable(false);
        projects.setIconTextGap(20);
        projects.setMargin(new java.awt.Insets(2, 14, 2, 35));
        projects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectsActionPerformed(evt);
            }
        });
        getContentPane().add(projects, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 240, 80));

        closeSesion.setBackground(new java.awt.Color(204, 0, 0));
        closeSesion.setText("Cerrar Sesion");
        closeSesion.setFocusable(false);
        closeSesion.setMargin(new java.awt.Insets(2, 10, 2, 14));
        closeSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeSesionActionPerformed(evt);
            }
        });
        getContentPane().add(closeSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 60, 110, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/agenda_1500px.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1110, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void managementAcademicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managementAcademicActionPerformed
        // TODO add your handling code here:
        WindowManagementAcademic newWindow=new WindowManagementAcademic(actualSes);
        newWindow.setLocationRelativeTo(null);
        newWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_managementAcademicActionPerformed

    private void makeHomeworksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeHomeworksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makeHomeworksActionPerformed

    private void eventsCalendaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventsCalendaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventsCalendaryActionPerformed

    private void libraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libraryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libraryActionPerformed

    private void projectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectsActionPerformed

    private void closeSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeSesionActionPerformed
        // TODO add your handling code here:
        WindowStartSesion newPage = new WindowStartSesion();
        newPage.setVisible(true);
        newPage.setLocationRelativeTo(null);
        
        Sesion.closeSesion();
        dispose();
    }//GEN-LAST:event_closeSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton closeSesion;
    private javax.swing.JButton contacts;
    private javax.swing.JButton eventsCalendary;
    private javax.swing.JButton library;
    private javax.swing.JButton makeHomeworks;
    private javax.swing.JButton managementAcademic;
    private javax.swing.JButton projects;
    // End of variables declaration//GEN-END:variables
}
