/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.grades;

import Data.CUTTING;
import Data.Course;
import Data.Files;
import Interface.WindowMain;
import Sesion.Sesion;
import java.awt.dnd.DropTarget;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro
 */
public class WindowCourseNotes extends javax.swing.JFrame {

    /**
     * Creates new form WindowCourseNotes
     */
    
    String url;
    String nameCourse;
    Course course;
    Files data=new Files(); 
    Sesion actualSesion;
    int y=10;
    int numCutting=3;
    
    /**
     *
     * @param course
     */
    public WindowCourseNotes(Course course, Sesion sesion){
        
        this.course=course;
        actualSesion=sesion;
        
        initComponents();
    }
    
    //Muestra el corte
    
    private void paintGrade(String nameGrade, String grade,String num){
        
        cutting panel=new cutting(num, course.getCutting(numCutting));
        //panel.setData(nameGrade,grade);
        //int h=panel.getMinimumSize().height-100;
        //int g=panel.getMinimumSize().width+100;
       
        this.jPanel1.add(panel,new org.netbeans.lib.awtextra.AbsoluteConstraints(5, y, 470, 180));
        jPanel1.updateUI();
        y=y+190;
    }
    
        
    
    private void updateProm(){
          this.jTextField5.setText(String.valueOf(course.calculateProm()));
     }


    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        nameGrade = new javax.swing.JLabel();
        addCutting = new javax.swing.JButton();
        start = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jDialog1.setBounds(new java.awt.Rectangle(30, 40, 50, 50));
        jDialog1.setSize(new java.awt.Dimension(50, 40));

        jTextPane1.setMinimumSize(new java.awt.Dimension(60, 40));
        jScrollPane2.setViewportView(jTextPane1);

        jDialog1.getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField4.setEditable(false);
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 84, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("PROMEDIO");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 230, 60));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 84, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("   DEF");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 3, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 240, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 510, 60));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(nameGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 8, 170, 25));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 510, 260));

        addCutting.setText("Añadir Corte");
        addCutting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCuttingActionPerformed(evt);
            }
        });
        getContentPane().add(addCutting, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, 30));

        start.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/pagina-de-inicio.png"))); // NOI18N
        start.setText("Inicio");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 110, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/agenda_1500px.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 760, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCuttingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCuttingActionPerformed
        // TODO add your handling code here:
       
        //REVISAR AQUI
        cutting panel=new cutting(String.valueOf((numCutting+1)), new CUTTING("", 0));
        numCutting++;
        
        //Quiero agregar un objeto de escucha para poder agrandar el panel de un corte
        //System.out.println(panel.getComponent(1).getSize());
        /*panel.getComponent(0).getComponentAt(-1, -1).addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                System.out.println("Aqui");
                panel.setSize(g, h);
                
            }
        });*/
       
        this.jPanel1.add(panel,new org.netbeans.lib.awtextra.AbsoluteConstraints(5, y, 470,180));
        DropTarget F=new DropTarget();
        
        jPanel1.setDropTarget(F);
        jPanel1.updateUI();
        y=y+190;
        
        
        //this.jButton1.setLocation(y, y);
    }//GEN-LAST:event_addCuttingActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        WindowMain newWindow=new WindowMain(actualSesion);
        newWindow.setLocationRelativeTo(null);
        newWindow.setVisible(true);
        dispose();

    }//GEN-LAST:event_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowCourseNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowCourseNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowCourseNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowCourseNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCutting;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel nameGrade;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
