/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.grades;
import Data.ChargeData;
import Data.Course;
import Interface.WindowMain;
import Sesion.Sesion;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro
 */
public class WindowManagementAcademic extends javax.swing.JFrame {

    /**
     * Creates new form WindowManagementAcademic
     */
    int y=35;
    boolean title=false;
    ChargeData data;
    Sesion actualSesion;
    
    public WindowManagementAcademic(Sesion sesion) {
        initComponents();
        actualSesion=sesion;
        
        
        setSemester(jComboBox1.getSelectedItem().toString(),jComboBox1.getSelectedIndex());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //Crea course y le envia como parametro la informacion del curso
    private void createCourse(Course course){
        
        WindowCourse n=new WindowCourse(course, actualSesion);
        n.setVisible(true);
        n.setNum(jPanel1.getComponentCount()-2);
        n.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 0, 0)));
        //Añade objeto listener al boton editar notas
        n.getComponent(3).addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                
                //obtiene el numero del curso
                deleteCourse(n.getNum());
                
            }
        });
        n.getComponent(2).addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                
                dispose();
                
            }
        });
        
       jPanel1.add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, y, 530, 50));
       jPanel1.updateUI();
       y=y+60;
    }
    
    private void deleteCourse(int num){
        data.deleteCourse(num);
        
        jPanel1.removeAll();
        jPanel1.updateUI();
        y=35;
        setSemester(jComboBox1.getSelectedItem().toString(),jComboBox1.getSelectedIndex());
       
    }
    
    private void paintTitlePanel(){
        
        javax.swing.JLabel titlePromActually=new javax.swing.JLabel("Promedio Actual");
        javax.swing.JLabel titleDef=new javax.swing.JLabel("Definitiva Actual");
        titlePromActually.setFont(new java.awt.Font("Tahoma", 1, 10));
        titleDef.setFont(new java.awt.Font("Tahoma", 1, 10));
        
        jPanel1.add(titlePromActually,new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 90, -1));
        jPanel1.add(titleDef,new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 20, 90, -1));
        title=true;
        
    }
    
    private void setSemester(String sem,int numSem){
        
        data=new ChargeData(actualSesion.userName,sem,numSem);
        
        this.paintTitlePanel();
        
         for(int i=0; i<data.getNumCourses();i++){
              
              createCourse(data.getCourse(i));
              
          }
         
       
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Addcourse = new javax.swing.JButton();
        start = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Addcourse.setText("Añadir curso");
        Addcourse.setFocusable(false);
        Addcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddcourseMouseClicked(evt);
            }
        });
        Addcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddcourseActionPerformed(evt);
            }
        });
        Addcourse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AddcourseKeyTyped(evt);
            }
        });
        getContentPane().add(Addcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 140, 30));

        start.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/pagina-de-inicio.png"))); // NOI18N
        start.setText("Inicio");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 120, 60));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 560, 290));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primer Semestre", "Segundo Semestre", "Tercer Semestre", "Cuarto Semestre", "Quinto Semestre", "Sexto Semestre", "Septimo Semestre", "Octavo Semestre", "Noveno Semestre", "Decimo Semestre" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 160, 40));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/agenda_1500px.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddcourseActionPerformed
        // TODO add your handling code here:
       String name=JOptionPane.showInputDialog(null, "Nombre Materia");
       
       //nombre tiene que ser distinto de null
       if( name!=null ){
           if(!name.equals("") ){ //nombre distinto de vacio
              this.data.addCourse(name);
               this.createCourse(data.getCourse(data.getNumCourses()-1));
               if(title==false){
               this.paintTitlePanel();
               } 
           }
       }
    }//GEN-LAST:event_AddcourseActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        WindowMain newWindow=new WindowMain(actualSesion);
        newWindow.setLocationRelativeTo(null);
        newWindow.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_startActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        jPanel1.removeAll();
        jPanel1.updateUI();
        y=35;
        setSemester(jComboBox1.getSelectedItem().toString(),jComboBox1.getSelectedIndex());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void AddcourseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AddcourseKeyTyped
        // TODO add your handling code here:
        System.out.println("Hola");
        
    }//GEN-LAST:event_AddcourseKeyTyped

    private void AddcourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddcourseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AddcourseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowManagementAcademic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowManagementAcademic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowManagementAcademic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowManagementAcademic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addcourse;
    private javax.swing.JLabel Background;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
